# Site settings
title: Vagrant Coder
email: xuxiaoxin@yuntiansoft.com
description: > # this means to ignore newlines until "baseurl:"
  这个Vagrant Coder用来写作的博客
# 
baseurl: "" # the subpath of your site, e.g. /blog

url: "http://vagrantcoder.github.io" # the base hostname & protocol for your site

twitter_username: xuxiaoxin
github_username:  xuxiaoxin


# Build settings
markdown: kramdown
timezone: Asia/Shanghai

highlighter:rouge
